### ISSUE TITLE
How to configure for typescripts?

### ISSUE THREAD

**Issue by hansiemithun** [yessky/hotrun#1]
Its a very good post, need to understand if there is a possibility to configure for typescript files to bundle, minify and uglify using this technique. A working example will be a great help

**Comment by yessky** [comment]
This techinque tries to avoid restart node.js app,  and hot compile changed modules on demand. For now, It's only used to speed-up your development for node.js app. It should works with webpack/webpack-dev-server/webpack-hot-middleware.

You can use webpack to bundle, minify and uglify for production env.

**Comment by yessky** [comment]
closed as no respond
