### ISSUE TITLE
Hotrun stops executing after first time reload

### ISSUE THREAD

**Issue by hansiemithun** [yessky/hotrun#2]
I have hotrun.json file:
`{
    "watch": ".",
    "force": [
        "./hotrun.json",
        "./app.js"
    ]
}`

Using KOA:

`const Koa = require('koa');
const app = new Koa();

app.use(async ctx => {
    ctx.body = 'Hello World';
});

app.listen(3000);`

First time when i change content from hello world to something else it works but with the error: `Error: listen EADDRINUSE :::3000`

Second time when i make change, repeats the same error. But this time stops execution

**Comment by yessky** [comment]
did you try my example, does it work? I can not reproduce your issuse.

**Comment by yessky** [comment]
close it as no respond
