### ISSUE TITLE
Getting Unable to resolve "true": unknown node or service

### ISSUE THREAD

**Issue by shahidcodes** [yessky/hotrun#3]
1. I am using [strapi.io@1.x](http://strapi.io) server. 
2. I installed hotrun globally
3. Happens only when i pass any argument such as -i or -w or -b `hotrun server.js -i -b -w api`
4. `hotrun server.js` seems working fine but does not do any hmr

**Comment by yessky** [comment]
1. `-i` option require a value, it's a port for node debugging
2. `-w` options also requires a value, it's a file/dir for watching to hmr
3. `-b` generally used with `-i`, it 's for node debugging and insert break points into your code;
2. `hotrun server.js` does not do hmr, as no files to watch changes. in this case, you can create a `hotrun.json` in your project root, see my example in `example/hotrun.json`

see README.md

```
-i, --inspect [port]             Enable inspect mode on port
-b, --inspect-brk                Enable inspect break mode
-c, --config                     Specify a json config file
-e, --extensions [extensions]    List of extensions to hook into [.es6,.js,.es,.jsx]
-w, --watch [dir]                Watch directory "dir" or files, to hot compile
-f, --force [dir]                Force restart if directory "dir" or files changed
-x, --exclude [dir]              Exclude matching directory/files from watcher
-p, --use-polling                In some filesystems watch events may not work correcly. This option enables "polling" which should mitigate this type of issues
-V, --version                    output the version number
-h, --help                       output usage information
```

**Comment by yessky** [comment]
if your problem was resovled, plz close the issue.

**Comment by shahidcodes** [comment]
Thanks. It worked. Although it didn't work with [Strapi](https://strapi.io/documentation/1.x.x/) server but it worked it my other express server. It maybe because strapi uses mounted type of procedure. So even though module cache is wiped something remains which doesn't require the module again. Any suggestions?

**Comment by yessky** [comment]
it seems `strapi` also exported as global command line, if that case both `hotrun` and `Strapi ` play as a node app runner

maybe show me your code piece, we can go ahead

**Comment by shahidcodes** [comment]
[Sample Strapi App](https://github.com/shahidcodes/strapi-app) 

[server.js](https://github.com/shahidcodes/strapi-app/blob/142c35485b7bd9cb269466291ef0681f822c4c3b/server.js#L13)

**Comment by yessky** [comment]
tested with your sampe app, works fine.

```json
"scripts": {
    "start": "hotrun -w api -f server.js server.js"
  }
```

<img width="751" alt="s1" src="https://user-images.githubusercontent.com/1220517/44241618-ac080180-a1f7-11e8-88e5-f107d5b5f7ac.png">

**Comment by yessky** [comment]
@shahidcodes  does it work ?

**Comment by shahidcodes** [comment]
Sorry @yessky for being late. I tested it seem working when I do something outside of exported controller object. Also I see this error
![tools](https://user-images.githubusercontent.com/17620737/44312217-40e64700-a412-11e8-9670-d748fe08dbc2.png)
when I remove that it works. Thats minor issue I can fix that.  But I could'nt make it work with any of the controllers or services.
Steps to reproduce:-
1. In any service like [email.js#L10](https://github.com/shahidcodes/strapi-app/blob/142c35485b7bd9cb269466291ef0681f822c4c3b/api/email/services/email.js#L10) add something.
2. Call this service from a controller like this [Email.js#L9](https://github.com/shahidcodes/strapi-app/blob/142c35485b7bd9cb269466291ef0681f822c4c3b/api/email/controllers/Email.js#L9)


Or try this ( as this is usually what i do )
1. In `api/emails/config/routes.json` add this object
```javascript
"GET /email/test" : {
  "controller": "Email",
  "action": "test",
  "policies": []
},
```
2. in `api/emails/controllers/Email.js` export this handler as test
```javascript
test: function * () {
  this.body = {num:1}
}
```
3. Restart the server to let strapi pick up the endpoint.
4. Then open `localhost:1337/email/test`
5. Change the num value and see if it reflects in the response
( it didnt work in my case)

**Comment by yessky** [comment]
I will fix it recently

**Comment by shahidcodes** [comment]
Great looking forward to try out the fix.

**Comment by yessky** [comment]
Try the fix plz

**Comment by shahidcodes** [comment]
It did'nt work. 
Here is what I did.
I created an endpoint `/hot` and a controller `hot` ( which is a generator function ) in exported object. 
1. I returned an object `{ a: 2 }` changing it didn't reflect in response.
2. I created a variable outside of `module.exports` and returned it in response. Changing that variable also did not work.
3. I created a module and exported a number from that module and I returned that module as response for `/hot`. This also did not work.

**Comment by yessky** [comment]
Now generator function is supported. please try the new version.

I'm considering to refactor, as current solution does not support change module export type, eg:

```
a.js
module.exports = 'string';

a.js updated
module.exports = function() {
  console.log('string to function')
};
```
